version: '3'

x-app-instance: &app-instance
  build: &app-build
    context: .
    dockerfile: Dockerfile
    args: &app-args
      VERSION: '${VERSION}'
  healthcheck:
    test: ['CMD', 'service', 'nginx', 'status']
    interval: 30s
    timeout: 20s
    retries: 5

services:
  core:
    <<: *app-instance
    image: ${REGISTRY_URL}/client:${VERSION}
    build:
      <<: *app-build
    ports:
      - 8088:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  manager:
    <<: *app-instance
    image: ${REGISTRY_URL}/client-manager:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.manager
    ports:
      - 8099:80
